/* 고객정보 생성 */
insert into "user" (user_id, user_name, created_at, modified_at) values ( 1, '홍길동', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values ( 2, '김길동', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values ( 3, '이길동', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values ( 4, '나길동', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values ( 5, '박길동', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values ( 6, '정길동', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values ( 7, '노길동', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values ( 8, '최길동', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values ( 9, '길길동', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (10, '문길동', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (11, '홍미나', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (12, '김미나', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (13, '이미나', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (14, '나미나', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (15, '박미나', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (16, '정미나', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (17, '노미나', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (18, '최미나', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (19, '길미나', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (20, '문미나', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (21, '홍걸출', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (22, '김걸출', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (23, '이걸출', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (24, '나걸출', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (25, '박걸출', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (26, '정걸출', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (27, '노걸출', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (28, '최걸출', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (29, '길걸출', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (30, '문걸출', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (31, '홍춘식', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (32, '김춘식', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (33, '이춘식', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (34, '나춘식', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (35, '박춘식', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (36, '정춘식', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (37, '노춘식', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (38, '최춘식', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (39, '길춘식', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (40, '문춘식', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (41, '홍을동', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (42, '김을동', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (43, '이을동', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (44, '나을동', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (45, '박을동', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (46, '정을동', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (47, '노을동', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (48, '최을동', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (49, '길을동', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (50, '문을동', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (51, '홍박식', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (52, '김박식', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (53, '이박식', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (54, '나박식', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (55, '박박식', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (56, '정박식', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (57, '노박식', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (58, '최박식', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (59, '길박식', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (60, '문박식', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (61, '홍찬호', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (62, '김찬호', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (63, '이찬호', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (64, '나찬호', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (65, '박찬호', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (66, '정찬호', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (67, '노찬호', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (68, '최찬호', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (69, '길찬호', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (70, '문찬호', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (71, '홍동렬', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (72, '김동렬', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (73, '이동렬', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (74, '나동렬', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (75, '박동렬', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (76, '정동렬', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (77, '노동렬', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (78, '최동렬', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (79, '길동렬', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (80, '문동렬', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (81, '홍상문', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (82, '김상문', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (83, '이상문', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (84, '나상문', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (85, '박상문', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (86, '정상문', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (87, '노상문', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (88, '최상문', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (89, '길상문', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (90, '문상문', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (91, '홍대화', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (92, '김대화', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (93, '이대화', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (94, '나대화', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (95, '박대화', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (96, '정대화', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (97, '노대화', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (98, '최대화', current_timestamp, current_timestamp);
insert into "user" (user_id, user_name, created_at, modified_at) values (99, '길대화', current_timestamp, current_timestamp);

/* 친구 가족 관계 생성 */


/* 스토어 정보 생성 */
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values ( 1, '맛나 분식' , 'A', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values ( 2, '달콤 분식' , 'A', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values ( 3, '매콤 분식' , 'A', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values ( 4, '학교앞 분식', 'A', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values ( 5, '문방구 분식', 'A', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values ( 6, '오늘 분식' , 'A', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values ( 7, '매일 분식' , 'A', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values ( 8, '지하철 분식', 'A', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values ( 9, '홍길동 분식', 'A', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (10, '길동 화장품', 'B', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (11, '코스모 화장품', 'B', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (12, '장미 화장품', 'B', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (13, '오늘 화장품', 'B', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (14, '매일 화장품', 'B', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (15, '꽃길 화장품', 'B', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (16, '다이나 화장품', 'B', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (17, '남몰래 화장품', 'B', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (18, '어여삐 화장품', 'B', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (19, '이름나 화장품', 'B', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (20, '빕스 레스토랑', 'B', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (21, '아웃백 레스토랑', 'C', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (22, '크라운 레스토랑', 'C', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (23, '하이트 레스토랑', 'C', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (24, '시티 레스토랑', 'C', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (25, 'TGIF 레스토랑', 'C', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (26, '토끼 레스토랑', 'C', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (27, '비프 레스토랑', 'C', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (28, '램 레스토랑', 'C', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (29, '크랩 레스토랑', 'C', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (30, '남산 레스토랑', 'C', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (31, '맛나 라면', 'A', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (32, '달콤 라면', 'A', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (33, '매콤  라면', 'A', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (34, '학교앞 라면', 'A', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (35, '문방구 라면', 'A', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (36, '오늘 라면', 'A', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (37, '매일  라면', 'A', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (38, '지하철 라면', 'A', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (39, '홍길동 라면', 'A', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (40, '길거리 라면', 'A', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (41, '길동 샾', 'B', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (42, '코스모 샾', 'B', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (43, '장미 샾', 'B', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (44, '오늘 샾', 'B', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (45, '매일 샾', 'B', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (46, '꽃길 샾', 'B', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (47, '다이나 샾', 'B', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (48, '남몰래 샾', 'B', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (49, '어여삐 샾', 'B', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (50, '이름나 샾', 'B', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (51, '빕스 코스요리', 'C', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (52, '아웃백 코스요리', 'C', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (53, '크라운 코스요리', 'C', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (54, '하이트 코스요리', 'C', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (55, '시티 코스요리', 'C', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (56, 'TGIF 코스요리', 'C', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (57, '토끼 코스요리', 'C', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (58, '비프 코스요리', 'C', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (59, '램 코스요리', 'C', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (60, '크랩 코스요리', 'C', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (61, '맛나 김밥', 'A', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (62, '달콤 김밥', 'A', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (63, '매콤 김밥', 'A', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (64, '학교앞 김밥', 'A', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (65, '문방구 김밥', 'A', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (66, '오늘 김밥', 'A', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (67, '매일 김밥', 'A', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (68, '지하철 김밥', 'A', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (69, '홍길동 김밥', 'A', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (70, '길동 스킨 테라피', 'A', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (71, '코스모 스킨 테라피', 'B', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (72, '장미 스킨 테라피', 'B', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (73, '오늘 스킨 테라피', 'B', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (74, '매일 스킨 테라피', 'B', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (75, '꽃길 스킨 테라피', 'B', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (76, '다이나 스킨 테라피', 'B', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (77, '남몰래 스킨 테라피', 'B', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (78, '어여삐 스킨 테라피', 'B', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (79, '이름나 스킨 테라피', 'B', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (80, '스타 스킨 테라피 ', 'B', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (81, '나폴리 파스타', 'C', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (82, '이태리 파스타', 'C', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (83, '프랑스 파스타', 'C', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (84, '동문 파스타', 'C', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (85, '남대문 파스타', 'C', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (86, '남산 파스타', 'C', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (87, '관악산 파스타', 'C', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (88, '월간 파스타', 'C', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (89, '냠냠 파스타', 'C', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (90, '맛나 냉면', 'C', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (91, '달콤 냉면', 'A', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (92, '매콤 냉면', 'A', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (93, '학교앞 냉면', 'A', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (94, '문방구 냉면', 'A', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (95, '오늘 냉면', 'A', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (96, '매일 냉면', 'A', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (97, '지하철 냉면', 'A', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (98, '홍길동 냉면', 'A', current_timestamp, current_timestamp);
insert into store (store_id, store_name, work_type_cd, created_at, modified_at) values (99, '강 냉면', 'A', current_timestamp, current_timestamp);

